// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TableMeta.proto
// Protobuf C++ Version: 4.24.0-main

#ifndef GOOGLE_PROTOBUF_INCLUDED_TableMeta_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_TableMeta_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_TableMeta_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_TableMeta_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_TableMeta_2eproto;
namespace toykv {
class PFieldMeta;
struct PFieldMetaDefaultTypeInternal;
extern PFieldMetaDefaultTypeInternal _PFieldMeta_default_instance_;
class PTableMeta;
struct PTableMetaDefaultTypeInternal;
extern PTableMetaDefaultTypeInternal _PTableMeta_default_instance_;
}  // namespace toykv
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace toykv {
enum PFieldMeta_PFieldType : int {
  PFieldMeta_PFieldType_INT = 0,
  PFieldMeta_PFieldType_FLOAT = 1,
  PFieldMeta_PFieldType_CHAR = 2,
  PFieldMeta_PFieldType_VARCHAR = 3,
  PFieldMeta_PFieldType_DATE = 4,
  PFieldMeta_PFieldType_PFieldMeta_PFieldType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  PFieldMeta_PFieldType_PFieldMeta_PFieldType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool PFieldMeta_PFieldType_IsValid(int value);
extern const uint32_t PFieldMeta_PFieldType_internal_data_[];
constexpr PFieldMeta_PFieldType PFieldMeta_PFieldType_PFieldType_MIN = static_cast<PFieldMeta_PFieldType>(0);
constexpr PFieldMeta_PFieldType PFieldMeta_PFieldType_PFieldType_MAX = static_cast<PFieldMeta_PFieldType>(4);
constexpr int PFieldMeta_PFieldType_PFieldType_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor*
PFieldMeta_PFieldType_descriptor();
template <typename T>
const std::string& PFieldMeta_PFieldType_Name(T value) {
  static_assert(std::is_same<T, PFieldMeta_PFieldType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to PFieldType_Name().");
  return PFieldMeta_PFieldType_Name(static_cast<PFieldMeta_PFieldType>(value));
}
template <>
inline const std::string& PFieldMeta_PFieldType_Name(PFieldMeta_PFieldType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PFieldMeta_PFieldType_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool PFieldMeta_PFieldType_Parse(absl::string_view name, PFieldMeta_PFieldType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PFieldMeta_PFieldType>(
      PFieldMeta_PFieldType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class PFieldMeta final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:toykv.PFieldMeta) */ {
 public:
  inline PFieldMeta() : PFieldMeta(nullptr) {}
  ~PFieldMeta() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR PFieldMeta(::google::protobuf::internal::ConstantInitialized);

  inline PFieldMeta(const PFieldMeta& from)
      : PFieldMeta(nullptr, from) {}
  PFieldMeta(PFieldMeta&& from) noexcept
    : PFieldMeta() {
    *this = ::std::move(from);
  }

  inline PFieldMeta& operator=(const PFieldMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline PFieldMeta& operator=(PFieldMeta&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PFieldMeta& default_instance() {
    return *internal_default_instance();
  }
  static inline const PFieldMeta* internal_default_instance() {
    return reinterpret_cast<const PFieldMeta*>(
               &_PFieldMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(PFieldMeta& a, PFieldMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(PFieldMeta* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PFieldMeta* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PFieldMeta* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PFieldMeta>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PFieldMeta& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const PFieldMeta& from) {
    PFieldMeta::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(PFieldMeta* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "toykv.PFieldMeta";
  }
  protected:
  explicit PFieldMeta(::google::protobuf::Arena* arena);
  PFieldMeta(::google::protobuf::Arena* arena, const PFieldMeta& from);
  const ::google::protobuf::MessageLite::ClassData* GetClassData() const final;
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  using PFieldType = PFieldMeta_PFieldType;
  static constexpr PFieldType INT = PFieldMeta_PFieldType_INT;
  static constexpr PFieldType FLOAT = PFieldMeta_PFieldType_FLOAT;
  static constexpr PFieldType CHAR = PFieldMeta_PFieldType_CHAR;
  static constexpr PFieldType VARCHAR = PFieldMeta_PFieldType_VARCHAR;
  static constexpr PFieldType DATE = PFieldMeta_PFieldType_DATE;
  static inline bool PFieldType_IsValid(int value) {
    return PFieldMeta_PFieldType_IsValid(value);
  }
  static constexpr PFieldType PFieldType_MIN = PFieldMeta_PFieldType_PFieldType_MIN;
  static constexpr PFieldType PFieldType_MAX = PFieldMeta_PFieldType_PFieldType_MAX;
  static constexpr int PFieldType_ARRAYSIZE = PFieldMeta_PFieldType_PFieldType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* PFieldType_descriptor() {
    return PFieldMeta_PFieldType_descriptor();
  }
  template <typename T>
  static inline const std::string& PFieldType_Name(T value) {
    return PFieldMeta_PFieldType_Name(value);
  }
  static inline bool PFieldType_Parse(absl::string_view name, PFieldType* value) {
    return PFieldMeta_PFieldType_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kTypeFieldNumber = 1,
    kLengthFieldNumber = 3,
    kNullableFieldNumber = 4,
  };
  // string name = 2;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // .toykv.PFieldMeta.PFieldType type = 1;
  void clear_type() ;
  ::toykv::PFieldMeta_PFieldType type() const;
  void set_type(::toykv::PFieldMeta_PFieldType value);

  private:
  ::toykv::PFieldMeta_PFieldType _internal_type() const;
  void _internal_set_type(::toykv::PFieldMeta_PFieldType value);

  public:
  // uint32 length = 3;
  void clear_length() ;
  ::uint32_t length() const;
  void set_length(::uint32_t value);

  private:
  ::uint32_t _internal_length() const;
  void _internal_set_length(::uint32_t value);

  public:
  // bool nullable = 4;
  void clear_nullable() ;
  bool nullable() const;
  void set_nullable(bool value);

  private:
  bool _internal_nullable() const;
  void _internal_set_nullable(bool value);

  public:
  // @@protoc_insertion_point(class_scope:toykv.PFieldMeta)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      29, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr name_;
    int type_;
    ::uint32_t length_;
    bool nullable_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TableMeta_2eproto;
};// -------------------------------------------------------------------

class PTableMeta final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:toykv.PTableMeta) */ {
 public:
  inline PTableMeta() : PTableMeta(nullptr) {}
  ~PTableMeta() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR PTableMeta(::google::protobuf::internal::ConstantInitialized);

  inline PTableMeta(const PTableMeta& from)
      : PTableMeta(nullptr, from) {}
  PTableMeta(PTableMeta&& from) noexcept
    : PTableMeta() {
    *this = ::std::move(from);
  }

  inline PTableMeta& operator=(const PTableMeta& from) {
    CopyFrom(from);
    return *this;
  }
  inline PTableMeta& operator=(PTableMeta&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PTableMeta& default_instance() {
    return *internal_default_instance();
  }
  static inline const PTableMeta* internal_default_instance() {
    return reinterpret_cast<const PTableMeta*>(
               &_PTableMeta_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(PTableMeta& a, PTableMeta& b) {
    a.Swap(&b);
  }
  inline void Swap(PTableMeta* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr &&
        GetArena() == other->GetArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PTableMeta* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PTableMeta* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<PTableMeta>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PTableMeta& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const PTableMeta& from) {
    PTableMeta::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  ::google::protobuf::internal::CachedSize* AccessCachedSize() const final;
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(PTableMeta* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "toykv.PTableMeta";
  }
  protected:
  explicit PTableMeta(::google::protobuf::Arena* arena);
  PTableMeta(::google::protobuf::Arena* arena, const PTableMeta& from);
  const ::google::protobuf::MessageLite::ClassData* GetClassData() const final;
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFieldsFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // repeated .toykv.PFieldMeta fields = 2;
  int fields_size() const;
  private:
  int _internal_fields_size() const;

  public:
  void clear_fields() ;
  ::toykv::PFieldMeta* mutable_fields(int index);
  ::google::protobuf::RepeatedPtrField< ::toykv::PFieldMeta >*
      mutable_fields();
  private:
  const ::google::protobuf::RepeatedPtrField<::toykv::PFieldMeta>& _internal_fields() const;
  ::google::protobuf::RepeatedPtrField<::toykv::PFieldMeta>* _internal_mutable_fields();
  public:
  const ::toykv::PFieldMeta& fields(int index) const;
  ::toykv::PFieldMeta* add_fields();
  const ::google::protobuf::RepeatedPtrField< ::toykv::PFieldMeta >&
      fields() const;
  // uint64 id = 1;
  void clear_id() ;
  ::uint64_t id() const;
  void set_id(::uint64_t value);

  private:
  ::uint64_t _internal_id() const;
  void _internal_set_id(::uint64_t value);

  public:
  // @@protoc_insertion_point(class_scope:toykv.PTableMeta)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {

        inline explicit constexpr Impl_(
            ::google::protobuf::internal::ConstantInitialized) noexcept;
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena);
        inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                              ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField< ::toykv::PFieldMeta > fields_;
    ::uint64_t id_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_TableMeta_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// PFieldMeta

// .toykv.PFieldMeta.PFieldType type = 1;
inline void PFieldMeta::clear_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.type_ = 0;
}
inline ::toykv::PFieldMeta_PFieldType PFieldMeta::type() const {
  // @@protoc_insertion_point(field_get:toykv.PFieldMeta.type)
  return _internal_type();
}
inline void PFieldMeta::set_type(::toykv::PFieldMeta_PFieldType value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:toykv.PFieldMeta.type)
}
inline ::toykv::PFieldMeta_PFieldType PFieldMeta::_internal_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return static_cast<::toykv::PFieldMeta_PFieldType>(_impl_.type_);
}
inline void PFieldMeta::_internal_set_type(::toykv::PFieldMeta_PFieldType value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.type_ = value;
}

// string name = 2;
inline void PFieldMeta::clear_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& PFieldMeta::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:toykv.PFieldMeta.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void PFieldMeta::set_name(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:toykv.PFieldMeta.name)
}
inline std::string* PFieldMeta::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:toykv.PFieldMeta.name)
  return _s;
}
inline const std::string& PFieldMeta::_internal_name() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.name_.Get();
}
inline void PFieldMeta::_internal_set_name(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.name_.Set(value, GetArena());
}
inline std::string* PFieldMeta::_internal_mutable_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* PFieldMeta::release_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:toykv.PFieldMeta.name)
  return _impl_.name_.Release();
}
inline void PFieldMeta::set_allocated_name(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.name_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.name_.IsDefault()) {
          _impl_.name_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:toykv.PFieldMeta.name)
}

// uint32 length = 3;
inline void PFieldMeta::clear_length() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.length_ = 0u;
}
inline ::uint32_t PFieldMeta::length() const {
  // @@protoc_insertion_point(field_get:toykv.PFieldMeta.length)
  return _internal_length();
}
inline void PFieldMeta::set_length(::uint32_t value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:toykv.PFieldMeta.length)
}
inline ::uint32_t PFieldMeta::_internal_length() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.length_;
}
inline void PFieldMeta::_internal_set_length(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.length_ = value;
}

// bool nullable = 4;
inline void PFieldMeta::clear_nullable() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.nullable_ = false;
}
inline bool PFieldMeta::nullable() const {
  // @@protoc_insertion_point(field_get:toykv.PFieldMeta.nullable)
  return _internal_nullable();
}
inline void PFieldMeta::set_nullable(bool value) {
  _internal_set_nullable(value);
  // @@protoc_insertion_point(field_set:toykv.PFieldMeta.nullable)
}
inline bool PFieldMeta::_internal_nullable() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.nullable_;
}
inline void PFieldMeta::_internal_set_nullable(bool value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.nullable_ = value;
}

// -------------------------------------------------------------------

// PTableMeta

// uint64 id = 1;
inline void PTableMeta::clear_id() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.id_ = ::uint64_t{0u};
}
inline ::uint64_t PTableMeta::id() const {
  // @@protoc_insertion_point(field_get:toykv.PTableMeta.id)
  return _internal_id();
}
inline void PTableMeta::set_id(::uint64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:toykv.PTableMeta.id)
}
inline ::uint64_t PTableMeta::_internal_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.id_;
}
inline void PTableMeta::_internal_set_id(::uint64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.id_ = value;
}

// repeated .toykv.PFieldMeta fields = 2;
inline int PTableMeta::_internal_fields_size() const {
  return _internal_fields().size();
}
inline int PTableMeta::fields_size() const {
  return _internal_fields_size();
}
inline void PTableMeta::clear_fields() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.fields_.Clear();
}
inline ::toykv::PFieldMeta* PTableMeta::mutable_fields(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:toykv.PTableMeta.fields)
  return _internal_mutable_fields()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::toykv::PFieldMeta>* PTableMeta::mutable_fields()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:toykv.PTableMeta.fields)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_fields();
}
inline const ::toykv::PFieldMeta& PTableMeta::fields(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:toykv.PTableMeta.fields)
  return _internal_fields().Get(index);
}
inline ::toykv::PFieldMeta* PTableMeta::add_fields() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::toykv::PFieldMeta* _add = _internal_mutable_fields()->Add();
  // @@protoc_insertion_point(field_add:toykv.PTableMeta.fields)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::toykv::PFieldMeta>& PTableMeta::fields() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:toykv.PTableMeta.fields)
  return _internal_fields();
}
inline const ::google::protobuf::RepeatedPtrField<::toykv::PFieldMeta>&
PTableMeta::_internal_fields() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.fields_;
}
inline ::google::protobuf::RepeatedPtrField<::toykv::PFieldMeta>*
PTableMeta::_internal_mutable_fields() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.fields_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace toykv


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::toykv::PFieldMeta_PFieldType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::toykv::PFieldMeta_PFieldType>() {
  return ::toykv::PFieldMeta_PFieldType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_TableMeta_2eproto_2epb_2eh
