// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TableMeta.proto

#include "TableMeta.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace toykv {

inline constexpr PFieldMeta::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        type_{static_cast< ::toykv::PFieldMeta_PFieldType >(0)},
        length_{0u},
        nullable_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PFieldMeta::PFieldMeta(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PFieldMetaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PFieldMetaDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PFieldMetaDefaultTypeInternal() {}
  union {
    PFieldMeta _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PFieldMetaDefaultTypeInternal _PFieldMeta_default_instance_;

inline constexpr PTableMeta::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : fields_{},
        id_{::uint64_t{0u}},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PTableMeta::PTableMeta(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct PTableMetaDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PTableMetaDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PTableMetaDefaultTypeInternal() {}
  union {
    PTableMeta _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PTableMetaDefaultTypeInternal _PTableMeta_default_instance_;
}  // namespace toykv
static ::_pb::Metadata file_level_metadata_TableMeta_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_TableMeta_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_TableMeta_2eproto = nullptr;
const ::uint32_t
    TableStruct_TableMeta_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::toykv::PFieldMeta, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::toykv::PFieldMeta, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::toykv::PFieldMeta, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::toykv::PFieldMeta, _impl_.length_),
        PROTOBUF_FIELD_OFFSET(::toykv::PFieldMeta, _impl_.nullable_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::toykv::PTableMeta, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::toykv::PTableMeta, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::toykv::PTableMeta, _impl_.fields_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::toykv::PFieldMeta)},
        {12, -1, -1, sizeof(::toykv::PTableMeta)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::toykv::_PFieldMeta_default_instance_._instance,
    &::toykv::_PTableMeta_default_instance_._instance,
};
const char descriptor_table_protodef_TableMeta_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\017TableMeta.proto\022\005toykv\"\253\001\n\nPFieldMeta\022"
    "*\n\004type\030\001 \001(\0162\034.toykv.PFieldMeta.PFieldT"
    "ype\022\014\n\004name\030\002 \001(\t\022\016\n\006length\030\003 \001(\r\022\020\n\010nul"
    "lable\030\004 \001(\010\"A\n\nPFieldType\022\007\n\003INT\020\000\022\t\n\005FL"
    "OAT\020\001\022\010\n\004CHAR\020\002\022\013\n\007VARCHAR\020\003\022\010\n\004DATE\020\004\";"
    "\n\nPTableMeta\022\n\n\002id\030\001 \001(\004\022!\n\006fields\030\002 \003(\013"
    "2\021.toykv.PFieldMetab\006proto3"
};
static ::absl::once_flag descriptor_table_TableMeta_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_TableMeta_2eproto = {
    false,
    false,
    267,
    descriptor_table_protodef_TableMeta_2eproto,
    "TableMeta.proto",
    &descriptor_table_TableMeta_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_TableMeta_2eproto::offsets,
    file_level_metadata_TableMeta_2eproto,
    file_level_enum_descriptors_TableMeta_2eproto,
    file_level_service_descriptors_TableMeta_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_TableMeta_2eproto_getter() {
  return &descriptor_table_TableMeta_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_TableMeta_2eproto(&descriptor_table_TableMeta_2eproto);
namespace toykv {
const ::google::protobuf::EnumDescriptor* PFieldMeta_PFieldType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_TableMeta_2eproto);
  return file_level_enum_descriptors_TableMeta_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t PFieldMeta_PFieldType_internal_data_[] = {
    327680u, 0u, };
bool PFieldMeta_PFieldType_IsValid(int value) {
  return 0 <= value && value <= 4;
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr PFieldMeta_PFieldType PFieldMeta::INT;
constexpr PFieldMeta_PFieldType PFieldMeta::FLOAT;
constexpr PFieldMeta_PFieldType PFieldMeta::CHAR;
constexpr PFieldMeta_PFieldType PFieldMeta::VARCHAR;
constexpr PFieldMeta_PFieldType PFieldMeta::DATE;
constexpr PFieldMeta_PFieldType PFieldMeta::PFieldType_MIN;
constexpr PFieldMeta_PFieldType PFieldMeta::PFieldType_MAX;
constexpr int PFieldMeta::PFieldType_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class PFieldMeta::_Internal {
 public:
};

PFieldMeta::PFieldMeta(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:toykv.PFieldMeta)
}
inline PROTOBUF_NDEBUG_INLINE PFieldMeta::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : name_(arena, from.name_),
        _cached_size_{0} {}

PFieldMeta::PFieldMeta(
    ::google::protobuf::Arena* arena,
    const PFieldMeta& from)
    : ::google::protobuf::Message(arena) {
  PFieldMeta* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, type_),
           offsetof(Impl_, nullable_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::nullable_));

  // @@protoc_insertion_point(copy_constructor:toykv.PFieldMeta)
}
inline PROTOBUF_NDEBUG_INLINE PFieldMeta::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void PFieldMeta::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, type_),
           0,
           offsetof(Impl_, nullable_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::nullable_));
}
PFieldMeta::~PFieldMeta() {
  // @@protoc_insertion_point(destructor:toykv.PFieldMeta)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PFieldMeta::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.name_.Destroy();
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
PFieldMeta::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::ClassData
      data = {
          PFieldMeta::MergeImpl,
           nullptr,  // OnDemandRegisterArenaDtor
           &::google::protobuf::Message::kDescriptorMethods,
      };
  return &data;
}
PROTOBUF_NOINLINE void PFieldMeta::Clear() {
// @@protoc_insertion_point(message_clear_start:toykv.PFieldMeta)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  ::memset(&_impl_.type_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.nullable_) -
      reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.nullable_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PFieldMeta::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 29, 2> PFieldMeta::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_PFieldMeta_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // bool nullable = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(PFieldMeta, _impl_.nullable_), 63>(),
     {32, 63, 0, PROTOBUF_FIELD_OFFSET(PFieldMeta, _impl_.nullable_)}},
    // .toykv.PFieldMeta.PFieldType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PFieldMeta, _impl_.type_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PFieldMeta, _impl_.type_)}},
    // string name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PFieldMeta, _impl_.name_)}},
    // uint32 length = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(PFieldMeta, _impl_.length_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(PFieldMeta, _impl_.length_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .toykv.PFieldMeta.PFieldType type = 1;
    {PROTOBUF_FIELD_OFFSET(PFieldMeta, _impl_.type_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string name = 2;
    {PROTOBUF_FIELD_OFFSET(PFieldMeta, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 length = 3;
    {PROTOBUF_FIELD_OFFSET(PFieldMeta, _impl_.length_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // bool nullable = 4;
    {PROTOBUF_FIELD_OFFSET(PFieldMeta, _impl_.nullable_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
    "\20\0\4\0\0\0\0\0"
    "toykv.PFieldMeta"
    "name"
  }},
};

::uint8_t* PFieldMeta::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:toykv.PFieldMeta)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // .toykv.PFieldMeta.PFieldType type = 1;
  if (this->_internal_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_type(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "toykv.PFieldMeta.name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // uint32 length = 3;
  if (this->_internal_length() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this->_internal_length(), target);
  }

  // bool nullable = 4;
  if (this->_internal_nullable() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        4, this->_internal_nullable(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:toykv.PFieldMeta)
  return target;
}

::size_t PFieldMeta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:toykv.PFieldMeta)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // .toykv.PFieldMeta.PFieldType type = 1;
  if (this->_internal_type() != 0) {
    total_size += 1 +
                  ::_pbi::WireFormatLite::EnumSize(this->_internal_type());
  }

  // uint32 length = 3;
  if (this->_internal_length() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_length());
  }

  // bool nullable = 4;
  if (this->_internal_nullable() != 0) {
    total_size += 2;
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void PFieldMeta::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PFieldMeta*>(&to_msg);
  auto& from = static_cast<const PFieldMeta&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:toykv.PFieldMeta)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_type() != 0) {
    _this->_internal_set_type(from._internal_type());
  }
  if (from._internal_length() != 0) {
    _this->_internal_set_length(from._internal_length());
  }
  if (from._internal_nullable() != 0) {
    _this->_internal_set_nullable(from._internal_nullable());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PFieldMeta::CopyFrom(const PFieldMeta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:toykv.PFieldMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PFieldMeta::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PFieldMeta::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PFieldMeta::InternalSwap(PFieldMeta* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PFieldMeta, _impl_.nullable_)
      + sizeof(PFieldMeta::_impl_.nullable_)
      - PROTOBUF_FIELD_OFFSET(PFieldMeta, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::google::protobuf::Metadata PFieldMeta::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_TableMeta_2eproto_getter, &descriptor_table_TableMeta_2eproto_once,
      file_level_metadata_TableMeta_2eproto[0]);
}
// ===================================================================

class PTableMeta::_Internal {
 public:
};

PTableMeta::PTableMeta(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:toykv.PTableMeta)
}
inline PROTOBUF_NDEBUG_INLINE PTableMeta::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from)
      : fields_{visibility, arena, from.fields_},
        _cached_size_{0} {}

PTableMeta::PTableMeta(
    ::google::protobuf::Arena* arena,
    const PTableMeta& from)
    : ::google::protobuf::Message(arena) {
  PTableMeta* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_);
  _impl_.id_ = from._impl_.id_;

  // @@protoc_insertion_point(copy_constructor:toykv.PTableMeta)
}
inline PROTOBUF_NDEBUG_INLINE PTableMeta::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : fields_{visibility, arena},
        _cached_size_{0} {}

inline void PTableMeta::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.id_ = {};
}
PTableMeta::~PTableMeta() {
  // @@protoc_insertion_point(destructor:toykv.PTableMeta)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void PTableMeta::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
PTableMeta::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::ClassData
      data = {
          PTableMeta::MergeImpl,
           nullptr,  // OnDemandRegisterArenaDtor
           &::google::protobuf::Message::kDescriptorMethods,
      };
  return &data;
}
PROTOBUF_NOINLINE void PTableMeta::Clear() {
// @@protoc_insertion_point(message_clear_start:toykv.PTableMeta)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.fields_.Clear();
  _impl_.id_ = ::uint64_t{0u};
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* PTableMeta::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 1, 0, 2> PTableMeta::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_PTableMeta_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .toykv.PFieldMeta fields = 2;
    {::_pbi::TcParser::FastMtR1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PTableMeta, _impl_.fields_)}},
    // uint64 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PTableMeta, _impl_.id_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PTableMeta, _impl_.id_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 id = 1;
    {PROTOBUF_FIELD_OFFSET(PTableMeta, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // repeated .toykv.PFieldMeta fields = 2;
    {PROTOBUF_FIELD_OFFSET(PTableMeta, _impl_.fields_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::toykv::PFieldMeta>()},
  }}, {{
  }},
};

::uint8_t* PTableMeta::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:toykv.PTableMeta)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this->_internal_id(), target);
  }

  // repeated .toykv.PFieldMeta fields = 2;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_fields_size()); i < n; i++) {
    const auto& repfield = this->_internal_fields().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(2, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:toykv.PTableMeta)
  return target;
}

::size_t PTableMeta::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:toykv.PTableMeta)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .toykv.PFieldMeta fields = 2;
  total_size += 1UL * this->_internal_fields_size();
  for (const auto& msg : this->_internal_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // uint64 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
        this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void PTableMeta::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<PTableMeta*>(&to_msg);
  auto& from = static_cast<const PTableMeta&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:toykv.PTableMeta)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_fields()->MergeFrom(
      from._internal_fields());
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PTableMeta::CopyFrom(const PTableMeta& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:toykv.PTableMeta)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool PTableMeta::IsInitialized() const {
  return true;
}

::_pbi::CachedSize* PTableMeta::AccessCachedSize() const {
  return &_impl_._cached_size_;
}
void PTableMeta::InternalSwap(PTableMeta* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.fields_.InternalSwap(&other->_impl_.fields_);
        swap(_impl_.id_, other->_impl_.id_);
}

::google::protobuf::Metadata PTableMeta::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_TableMeta_2eproto_getter, &descriptor_table_TableMeta_2eproto_once,
      file_level_metadata_TableMeta_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace toykv
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
