// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ToykvService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::toykv;

class ToykvServiceHandler : virtual public ToykvServiceIf {
 public:
  ToykvServiceHandler() {
    // Your initialization goes here
  }

  void Insert( ::toykv::TDmlRes& _return, const  ::toykv::TInsertReq& insertReq) {
    // Your implementation goes here
    printf("Insert\n");
  }

  void Delete( ::toykv::TDmlRes& _return, const  ::toykv::TDeleteReq& deleteReq) {
    // Your implementation goes here
    printf("Delete\n");
  }

  void CreateTable( ::toykv::TDdlRes& _return, const  ::toykv::TCreateTableReq& createTableReq) {
    // Your implementation goes here
    printf("CreateTable\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<ToykvServiceHandler> handler(new ToykvServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new ToykvServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

